11. Задания и исполнители
htmlacademy-yii/605869-task-force-1 pull request #11
Opened 2020-11-04 13:26 UTC by IgorRusaleev

2020-11-05 12:04 UTC, andrewverner requested changes

2020-11-05 12:04 UTC, denis-khodakovskiy commented on frontend/controllers/TasksController.php
> +        $tasks = \frontend\models\Task::find()->where(['status_id' => 1])->all();
1. Постоянные переменные лучше выносить в константы. Представь, что задание может принимать 50 различных статусов и тебе надо все эти статусы использовать в разных частях кода. Оперировать просто цифрами не удобно. Кроме того, если идентификатор какого-то из статусов изменится, то его надо будет везде в коде поменять, а если этот статус используется в сотне мест, то внести правки будет сложно. Заведи константы в модели задания Task

```php
const STATUS_NEW = 1;
const STATUS_COMPLETED = 5;
```
и т.д. и используй их вместо цифр, как здесь

`Task::find()->where(['status_id' => Task::STATUS_NEW])->all();`. В такой записи сразу понятно, задания в в каком статусе ты выбираешь. Лучше, чем `['status_id' => 24]`

2. Если ты используешь классы, которые находятся в пространстве имён отличном от пространства текущего класса, то их подключение надо выносить в блок `use`:

```php
namespace frontend\controllers;

use frontend\models\Task;

/**
 * Class tasksController
 * @package frontend\controllers
 */
class TasksController extends \yii\web\Controller
{
    /**
     * @return string
     */
    public function actionIndex()
    {
        $tasks = Task::find()->where(['status_id' => 1])->all();
        //...
    }
}
```

2020-11-05 12:04 UTC, andrewverner commented on frontend/controllers/TasksController.php
> +use TaskForce\Task;
Ты не ту модель подключил. Надо подключать `frontend\models\Task`

2020-11-05 12:04 UTC, andrewverner commented on frontend/controllers/UsersController.php
> +use frontend\models\Task;
Модель задания в этом классе не используется. Это подключение тут лишнее

2020-11-05 12:04 UTC, andrewverner commented on frontend/controllers/UsersController.php
> +        return $this->render('index', [
По рекомендациям PSR перед `return` нужно оставлять пустую строку

2020-11-05 12:04 UTC, andrewverner commented on frontend/views/users/index.php
> +</section>
Все файлы с расширением `php` в конце должны иметь пустую строку

2020-11-06 05:12 UTC, IgorRusaleev commented on frontend/controllers/TasksController.php
> +        $tasks = \frontend\models\Task::find()->where(['status_id' => 1])->all();
+++

2020-11-06 05:13 UTC, IgorRusaleev commented on frontend/controllers/TasksController.php
> +use TaskForce\Task;
+++

2020-11-06 05:16 UTC, IgorRusaleev commented on frontend/controllers/UsersController.php
> +use frontend\models\Task;
используются константы

2020-11-06 05:20 UTC, IgorRusaleev commented on frontend/controllers/UsersController.php
> +use frontend\models\Task;
+++

2020-11-06 05:58 UTC, IgorRusaleev commented on frontend/controllers/UsersController.php
> +        return $this->render('index', [
+++

2020-11-06 05:59 UTC, IgorRusaleev commented on frontend/views/users/index.php
> +</section>
+++

2020-11-07 09:59 UTC, merged