Избирательное поведение
htmlacademy-yii/605869-task-force-1 pull request #12
Opened 2020-11-30 20:08 UTC by IgorRusaleev

2020-12-06 15:59 UTC, andrewverner requested changes

2020-12-06 15:59 UTC, andrewverner commented on frontend/controllers/UsersController.php
> +        $this->enableCsrfValidation = false;
Зачем валидацию csrf выключил?

2020-12-06 15:59 UTC, andrewverner commented on frontend/controllers/TasksController.php
> +        $this->enableCsrfValidation = false;
Зачем валидацию csrf выключил?

2020-12-07 09:19 UTC, IgorRusaleev commented on frontend/controllers/UsersController.php
> +        $this->enableCsrfValidation = false;
включил

2020-12-07 09:20 UTC, IgorRusaleev commented on frontend/controllers/TasksController.php
> +        $this->enableCsrfValidation = false;
включил

2020-12-09 13:00 UTC, merged