Module1 task2
htmlacademy-yii/605869-task-force-1 pull request #2
Opened 2020-03-28 12:27 UTC by IgorRusaleev

2020-03-29 07:33 UTC, nikserg reviewed
Отлично постарался! Задание не простое, но ты движешься в правильном направлении.

2020-03-29 07:33 UTC, nikserg commented on composer-setup.php
> +<?php
composer-setup.php и composer.phar лучше исключить из репозитория. Сам composer можно установить глобально в системе и запускать просто командой `composer`, в проекте он не нужен.

2020-03-29 07:33 UTC, nikserg commented on src/Task.php
> +        const STATUS_NEW = 'new';
К статусам лучше написать комментарии, чтобы потом было понятно, где что. Пока пишешь код - держишь все в голове, кажется, что это само собой разумеется, но буквально через неделю уже начинаешь путаться, да и другим будет проще понять, если есть комментарии.

2020-03-29 07:33 UTC, nikserg commented on src/Task.php
> +        const STATUS_CANCEL = 'status_cancel';
У тебя есть `STATUS_NEW`, который имеет значение `new`, и `STATUS_IN_WORK`, который имеет значение `status_in_work`. Тут нужно определиться: либо мы включаем тип (status_) в значение константы, либо нет. Я бы предпочел не включать. У тебя уже прописан тип в имени константы - это ты очень хорошо и правильно сделал - и этого достаточно.

2020-03-29 07:33 UTC, nikserg commented on src/Task.php
> +        private $idPerformer = [];
1. Хороший тон - оставлять аннотацию для каждого члена класса, с ожидаемым типом переменной и кратким комментарием. В IDE PhpStorm это встроенная функция: напиши /** над строкой с объявлением члена класса, нажми enter и он сформирует болванку под аннотацию.
2. idPerformer - это будет integer, а не массив.

2020-03-29 07:33 UTC, nikserg commented on src/Task.php
> +        public function __construct($idPerformer, $idCustomer)
Также нужно добавить аннотацию конструктору с типами переменных. Вообще, чем больше аннотаций, тем лучше читается код. Рекомендую тебе лепить их вообще ко всем классам, членам классов, методам классов.

2020-03-29 07:33 UTC, nikserg commented on src/Task.php
> +                case 'new':
В коде нужно использовать константы, которые ты определил в начале класса, а не их значения. Это также касается кода ниже.

2020-03-29 07:33 UTC, nikserg commented on src/Task.php
> +                    $statuses [action_respond] = 'status_in_work';
1. statuses должна быть объявлена в начале функции
2. action_respond => Task::ACTION_RESPOND, если ты хочешь обратиться к константе

2020-03-29 07:33 UTC, nikserg commented on src/Task.php
> +            return $statuses;
Мне кажется, функция делает что-то не то. В задании сказано: "возвращать имя статуса, в который перейдёт задание после выполнения конкретного действия". Имеется в виду перейдет из текущего статуса (который хранится в $this->status). То есть, функция должна принимать ДЕЙСТВИЕ и возвращать плоский массив статусов.

2020-03-29 07:33 UTC, nikserg commented on src/Task.php
> +            $status = $Task -> status;
Наверно, ты имел в виду $this?

2020-03-29 07:33 UTC, nikserg commented on src/Task.php
> +            return $status;
Еще в рамках этого задания нужно будет сделать несложное тестирование. В задании даже был пример проверки: assert($strategy->getNextStatus('action_cancel') == Task::STATUS_CANCEL, 'cancel action');

2020-04-05 08:03 UTC, nikserg requested changes
В целом направление верное, нужно внести несколько правок.

2020-04-05 08:03 UTC, nikserg commented on src/Task.php
> +                case 'ACTION_RESPOND':
У тебя вместо имени константы строка, содержащая имя константы. Это не сработает.

2020-04-05 08:03 UTC, nikserg commented on src/Task.php
> +                    $status = '';
Если не передано ни одно из известных действий, логично было бы выкидывать исключение.

2020-04-05 08:03 UTC, nikserg commented on src/Task.php
> +//            $status = $this->status;
Закомментированный код не стоит пушить в боевой репозиторий. Оставляй его на время разработки, а потом удаляй.

2020-04-05 08:03 UTC, nikserg commented on src/Task.php
> +            return ['new' => 'Новый',
В целом метод верный, но нужно использовать константы.

2020-04-05 08:03 UTC, nikserg commented on src/Task.php
> +            return ['action_cancel' => 'Отменить',
Аналогично, нужно использовать константы.

2020-04-05 08:03 UTC, nikserg commented on src/Task.php
> +                case 'STATUS_NEW':
Здесь та же ошибка, строка с именем константы вместо собственно константы.

2020-04-05 08:03 UTC, nikserg commented on src/Task.php
> +                    $action = ['ACTION_RESPOND', 'ACTION_CANCEL'];
Тут тоже нужно константы использовать.

2020-04-05 08:03 UTC, nikserg commented on src/Task.php
> +            $status = $this->status;
По сути, переменная `$status` лишняя, поскольку она только в следующей строке используется. Можно написать сразу `switch ($this->status)`

2020-04-05 08:03 UTC, nikserg commented on src/Task.php
> +                    $action = [];
Если не передан ни один из известных статусов, логично выкидывать исключение.

2020-04-05 08:03 UTC, nikserg commented on src/test.php
> +require_once 'Task.php';
Сначала `require`, потом `use`.

2020-04-05 08:03 UTC, nikserg commented on src/test.php
> +$idPerformer = '1';
Тут строки, а должны быть числа

2020-04-05 08:03 UTC, nikserg commented on src/test.php
> +$strategy = new \TaskForce\src\Task($idPerformer, $idCustomer);
Ты уже написал use, в принципе достаточно `$strategy = new Task($idPerformer, $idCustomer)`

2020-04-05 09:01 UTC, IgorRusaleev commented on src/Task.php
> +                    $status = '';
я не понял про исключение. Это: default: $status = $this->status; ?

2020-04-05 09:06 UTC, IgorRusaleev commented on src/Task.php
> +            return ['new' => 'Новый',
не совсем понял как использовать константы. Сделаю как думаю.

2020-04-05 09:06 UTC, IgorRusaleev commented on src/Task.php
> +            return ['action_cancel' => 'Отменить',
не совсем понял как использовать константы. Сделаю как думаю.

2020-04-05 09:47 UTC, IgorRusaleev commented on src/test.php
> +$strategy = new \TaskForce\src\Task($idPerformer, $idCustomer);
Поправил все замечания. Класс не проходит тестирование. Ошибка. PHP Parse error:  syntax error, unexpected 'int' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /opt/lampp/htdocs/605869-task-force-1/src/Task.php on line 30

2020-04-08 12:28 UTC, merged