На пути к совершенству
htmlacademy-yii/605869-task-force-1 pull request #5
Opened 2020-05-04 19:23 UTC by IgorRusaleev

2020-05-05 07:03 UTC, nikserg requested changes
Честно говоря, я приятно удивлен, что ты с первого раза и сам уловил суть абстрактных классов и полиморфизма, у меня в свое время с этим большие проблемы были. Нужно немного причесать способ работы с ними, но сама идея фундаментально на 100% правильно понята.

2020-05-05 07:03 UTC, nikserg commented on src/AbstractSelectingAction.php
> +namespace TaskForce;
Наша структура классов усложняется. Появляется отдельная ветка наследования - для действий. Логично вынести их в отдельный неймспейс и отдельную папку. Например, `TaskForce\Action`

2020-05-05 07:03 UTC, nikserg commented on src/AbstractSelectingAction.php
> + * абстрактный класс задаёт три абстрактных метода: для возврата названия, внутреннего имени и для проверки прав
Комментарий должен описывать суть происходящего, которая не бросается в глаза при взгляде на код. Сравни:
`public $x = 5; //Объявляем переменную x и присваиваем ей значение 5`
и
`public $x=5; //Коэффициент усиления входного сигнала`

2020-05-05 07:03 UTC, nikserg commented on src/AbstractSelectingAction.php
> +namespace TaskForce;
И в этот неймспейс сложить как абстрактный класс, так и его наследников.

2020-05-05 07:03 UTC, nikserg commented on src/Task.php
> +        private $nameOfAction_refuse; // имя 'Отказаться'
Тут тебя немножко не в ту степь понесло. Есть небольшой лайфхак для самопроверки: если единственный способ решить задачу - писать много повторяющегося кода, значит ты что-то делаешь не так. Представь, если у тебя добавится еще одно действие, тебе придется добавлять еще одну переменную в класс, и еще один метод типа `actionRespond`. Это не может быть правильным. Значит, изначально что-то не так. 
Лучше голосом объясню.

2020-05-05 07:03 UTC, nikserg commented on src/AbstractSelectingAction.php
> +    abstract public function internalNameOfAction($idPerformer, $idCustomer, $idUser); //метод для возврата внутреннего имени
Этот метод не обязателен. В качестве внутреннего имени можно использовать имя самого класса.

2020-05-05 07:03 UTC, nikserg commented on src/AbstractSelectingAction.php
> +    abstract public function nameOfAction($idPerformer, $idCustomer, $idUser); //метод для возврата названия
Название действия никак не зависит от id пользователей, оно всегда одинаковое для класса. Поэтому метод может не принимать аргументов.

2020-05-05 14:27 UTC, IgorRusaleev commented on src/AbstractSelectingAction.php
> +namespace TaskForce;
исправил

2020-05-05 14:30 UTC, IgorRusaleev commented on src/AbstractSelectingAction.php
> + * абстрактный класс задаёт три абстрактных метода: для возврата названия, внутреннего имени и для проверки прав
поправил, но неуверен что понял как правильно закоментировать

2020-05-05 14:51 UTC, IgorRusaleev commented on src/AbstractSelectingAction.php
> +    abstract public function internalNameOfAction($idPerformer, $idCustomer, $idUser); //метод для возврата внутреннего имени
в абстрактном классе и дочерних классах метод удалил. В Task.php поправил

2020-05-05 15:50 UTC, IgorRusaleev commented on src/AbstractSelectingAction.php
> +namespace TaskForce;
я только не понял почему composer не подключает новый неймспейс, пришлось применить: use TaskForceAction\AbstractSelectingAction. Как автозагрузку composer настроить?

2020-05-05 16:16 UTC, IgorRusaleev commented on src/AbstractSelectingAction.php
> +    abstract public function nameOfAction($idPerformer, $idCustomer, $idUser); //метод для возврата названия
исправил

2020-05-06 08:08 UTC, nikserg commented on action/AbstractSelectingAction.php
> +    abstract public function checkingUserStatus($idPerformer, $idCustomer, $idUser); //метод для проверки прав
public function getInternalName() {
return get_called_class();
}

2020-05-06 08:19 UTC, nikserg requested changes

2020-05-06 08:19 UTC, nikserg commented on src/Task.php
> -                    $availableActions = [self::ACTION_RESPOND, self::ACTION_CANCEL];
$availableActions = [new ActionRespond(), new ActionCancel()];

2020-05-08 10:50 UTC, nikserg requested changes
Требуется доработка, обсуждали в Телеграме ошибки.

2020-05-08 10:50 UTC, nikserg commented on src/Action/ActionCancel.php
> +class ActionCancel extends AbstractSelectingAction
Небольшое замечание по неймингу. Можешь это позже исправить инструментом рефакторинга.
Я не рекомендую делать имена классов избыточными. Полное имя класса (включая неймспейс): TaskForce\Action\ActionCancel. Слово "Action" повторяется дважды. Из того, что класс в неймспейсе action, уже следует, что он является действием. Поэтому класс достаточно назвать просто Cancel.
У моего подхода есть противники, которые считают, что короткие имена классов затрудняют чтение кода, поэтому выбирай сам.

2020-05-08 10:50 UTC, nikserg commented on src/Action/ActionCancel.php
> +        if ($this->$checkingStatus)
Про эту ошибку я говорил. $this->$checkingStatus => $this->checkingStatus

2020-05-08 10:50 UTC, nikserg commented on src/Action/ActionCancel.php
> +        $checkingStatus = $this->checkingStatus;
Непонятно, почему вообще здесь эта переменная и эта проверка. Метод должен всегда возвращать одно и то же значение, независимо от переменных.
public function nameOfAction()
{
return "Отмена";
}

2020-05-08 10:50 UTC, nikserg commented on src/Action/ActionCancel.php
> +        $checkingStatus = $this->checkingStatus;
Аналогично, условия не нужны

2020-05-08 10:50 UTC, nikserg commented on src/Action/ActionCancel.php
> +        return ($this->checkingStatus = ($idCustomer == $idUser));
Тут можно просто возвращать true, если действие доступно и false в обратном случае. Внутренняя переменная checkingStatus откровенно лишняя.

2020-05-08 10:50 UTC, nikserg commented on src/Action/ActionDone.php
> +class ActionDone extends AbstractSelectingAction
Все замечания из ActionCancel касаются и остальных действий.

2020-05-08 16:16 UTC, IgorRusaleev commented on src/Action/ActionCancel.php
> +class ActionCancel extends AbstractSelectingAction
исправил

2020-05-08 18:33 UTC, IgorRusaleev commented on src/Action/ActionCancel.php
> +        if ($this->$checkingStatus)
исправил

2020-05-08 18:34 UTC, IgorRusaleev commented on src/Action/ActionCancel.php
> +        $checkingStatus = $this->checkingStatus;
исправил

2020-05-08 19:07 UTC, IgorRusaleev commented on src/Action/ActionCancel.php
> +        return ($this->checkingStatus = ($idCustomer == $idUser));
исправил

2020-05-08 19:08 UTC, IgorRusaleev commented on src/Action/ActionCancel.php
> +        $checkingStatus = $this->checkingStatus;
исправил

2020-05-08 19:08 UTC, IgorRusaleev commented on src/Action/ActionDone.php
> +class ActionDone extends AbstractSelectingAction
исправил

2020-05-12 06:56 UTC, nikserg requested changes
Некоторые моменты все еще не доработаны.

2020-05-12 06:56 UTC, nikserg commented on src/Action/Done.php
> +        if ($this->$checkingStatus)
Снова у тебя вместо обращения к `$this->checkingStatus` обращение к $this->$checkingStatus

2020-05-12 06:56 UTC, nikserg commented on src/Action/Done.php
> +    public function nameOfAction($idPerformer, $idCustomer, $idUser)
Насколько я помню, проговаривали, что nameOfAction не должна принимать никаких аргументов.

2020-05-12 06:56 UTC, nikserg commented on src/Action/Done.php
> +        public function internalNameOfAction($idPerformer, $idCustomer, $idUser)
Аналогично `internalNameOfAction` не должна принимать аргументов.

2020-05-12 06:56 UTC, nikserg commented on src/Task.php
> +        public function getNextStatus ()
А почему getNextStatus перестал принимать действие в качестве аргумента? Как функция узнает, какое действие меняет статус?

2020-05-12 06:56 UTC, nikserg commented on src/test.php
> -assert($strategy->getNextStatus('action_cancel') == \TaskForce\Task::STATUS_CANCEL, 'cancel action');
В тестировании должно появиться несколько ассертов, для тестирования разных случаев: когда idPerformer и idCustomer разные, когда одинаковые, с разными действиями.

2020-05-12 11:16 UTC, IgorRusaleev commented on src/Action/Done.php
> +        if ($this->$checkingStatus)
исправил

2020-05-12 11:17 UTC, IgorRusaleev commented on src/Action/Done.php
> +    public function nameOfAction($idPerformer, $idCustomer, $idUser)
исправил

2020-05-12 11:17 UTC, IgorRusaleev commented on src/Action/Done.php
> +        public function internalNameOfAction($idPerformer, $idCustomer, $idUser)
исправил

2020-05-12 13:35 UTC, IgorRusaleev commented on src/Task.php
> +        public function getNextStatus ()
исправил

2020-05-12 13:41 UTC, IgorRusaleev commented on src/test.php
> -assert($strategy->getNextStatus('action_cancel') == \TaskForce\Task::STATUS_CANCEL, 'cancel action');
По заданию: "Этот метод принимает id исполнителя задания, id заказчика задания и id текущего пользователя. Метод возвращает true или false в зависимости от доступности выполнения этого действия. " Сейчас test.php реализован по другому. У меня возникла старая проблема с подключением класса в этом файле. Почему task не подключается?

2020-05-12 13:41 UTC, IgorRusaleev commented on src/test.php
> -assert($strategy->getNextStatus('action_cancel') == \TaskForce\Task::STATUS_CANCEL, 'cancel action');
PHP Fatal error:  Uncaught Error: Class 'TaskForce\Task' not found in /opt/lampp/htdocs/605869-task-force-1/src/test.php:11

2020-05-13 07:43 UTC, nikserg requested changes
Все еще нужно поработать над nameOfAction и internalNameOfAction

2020-05-13 07:43 UTC, nikserg commented on src/Action/Cancel.php
> +        $idPerformer = $this->idPerformer;
Не очень понятно, что делает эта функция, зачем проверки. В моем представлении, она выглядит так:
public function nameOfAction()
    {
return 'Отменить';
}

2020-05-13 07:43 UTC, nikserg commented on src/Action/Cancel.php
> +    public function internalNameOfAction()
Замечания, аналогичные для nameOfAction

2020-05-13 07:43 UTC, nikserg commented on src/Action/Respond.php
> +        return $idPerformer == $idUser;
Получается, когда пользователь откликается на задание, он еще не исполнитель. Я бы сделал возможность для всех пользователей, кроме автора задачи.

2020-05-13 07:43 UTC, nikserg commented on src/Task.php
> +        public function __construct($idPerformer, $idCustomer, $idUser)
А idUser - это чей айдишник?

2020-05-13 07:43 UTC, nikserg commented on src/test.php
> -assert($strategy->getNextStatus('action_cancel') == \TaskForce\Task::STATUS_CANCEL, 'cancel action');
Нужно смотреть, так по коду вроде все в порядке.

2020-05-13 14:24 UTC, IgorRusaleev commented on src/Action/Cancel.php
> +        $idPerformer = $this->idPerformer;
исправил

2020-05-13 14:53 UTC, IgorRusaleev commented on src/Task.php
> +        public function __construct($idPerformer, $idCustomer, $idUser)
idUser - это id текущего пользователя

2020-05-13 15:06 UTC, IgorRusaleev commented on src/Action/Respond.php
> +        return $idPerformer == $idUser;
иправил

2020-05-15 08:02 UTC, nikserg requested changes

2020-05-15 08:02 UTC, nikserg commented on src/Task.php
> +            foreach ($this->$AvailableActions as $availableAction)
Опять обращение к элементу класса с именем, хранящимся в переменной $AvailableActions

2020-05-15 08:02 UTC, nikserg commented on src/Task.php
> +            $AvailableActions = $this->action;
Именовать переменные нужно в camelCase: начинаются обязательно со строчной буквы.

2020-05-15 08:02 UTC, nikserg commented on src/Action/Respond.php
> +        if ($idUser !== $idCustomer) return true;
В условиях всегда нужно использовать фигурные скобки, даже если они не обязательны.
Подумай еще, что этот код можно сократить до 
`return ($idUser !== $idCustomer)`

2020-05-15 08:02 UTC, nikserg commented on src/Action/Respond.php
> +        if ($idUser !== $idCustomer) return true;
Это же касается и других классов.

2020-05-22 14:36 UTC, IgorRusaleev commented on src/Task.php
> +            foreach ($this->$AvailableActions as $availableAction)
исправил

2020-05-22 14:41 UTC, IgorRusaleev commented on src/Task.php
> +            $AvailableActions = $this->action;
у меня эта функция уже переделана (я поменял switch на if)

2020-05-22 14:54 UTC, IgorRusaleev commented on src/Action/Respond.php
> +        if ($idUser !== $idCustomer) return true;
исправил

2020-05-27 09:48 UTC, nikserg requested changes
Написал пару замечаний по комментариям. Не увидел ответов на некоторые свои комментарии. Давай как договаривались: обрабатываешь мой комментарий - оставляешь какой-то знак, что он обработан, хотя бы просто плюсик.
Если проблемы с неймспейсом сохраняются, могу позже подключиться, пиши в телегу.

2020-05-27 09:48 UTC, nikserg commented on src/Action/AbstractSelectingAction.php
> + * абстрактный класс действий
Исключай из комментариев очевидное. То, что класс абстрактный, и так видно по коду. А вот что такое "действие" как раз никак не понятно. Можно написать, например, "Действие, которое теоретически может совершить пользователь: например, взять задачу, закрыть задачу и так далее"

2020-05-27 09:48 UTC, nikserg commented on src/Action/AbstractSelectingAction.php
> +    abstract public function nameOfAction(); //метод для возврата названия
Снова по поводу комментария. Очевидно, что name=название, и что комментарий относится к методу. А вот чем name отличается от internalName в местных терминах -  не понятно. Можно было бы написать, что первый метод - для человекопонятного названия действия, а второй - для машинного.
Если не знаешь, как хорошо написать комментарий - напиши просто пару примеров. Зачастую примеры говорят сами за себя. В данном случае можно написать пару примеров значений этой функции ("Отмена", "Взять в работу").
Это же справедливо и для остальных комментариев.

2020-05-31 07:16 UTC, IgorRusaleev commented on src/Action/AbstractSelectingAction.php
> + * абстрактный класс действий
+

2020-05-31 07:28 UTC, IgorRusaleev commented on src/Action/AbstractSelectingAction.php
> +    abstract public function nameOfAction(); //метод для возврата названия
++

2020-05-31 07:28 UTC, IgorRusaleev commented on src/Action/AbstractSelectingAction.php
> + * абстрактный класс действий
++

2020-06-01 06:54 UTC, nikserg commented on src/Action/AbstractSelectingAction.php
> +    abstract public function nameOfAction(); //метод для возврата названия
Отличный комментарий.

2020-06-01 07:03 UTC, nikserg requested changes

2020-06-01 07:03 UTC, nikserg commented on composer.json
> +    "name": "igor-rusaleev/task-force",
А куда пропал блок autoload? У тебя без него работает?

2020-06-01 07:03 UTC, nikserg commented on src/Action/Cancel.php
> +    protected $idPerformer;
Зачем нужны защищенные  $idPerformer, $idCustomer и $idUser? В коде не используются.

2020-06-01 07:03 UTC, nikserg commented on src/Action/Cancel.php
> +    public function checkingUserStatus($idPerformer, $idCustomer, $idUser)
Ты сделал функцию checkingUserStatus, однако она нигде не используется. По идее, она должна использоваться в getAvailableActions для определения списка доступных действий.

2020-06-01 07:03 UTC, nikserg commented on src/Task.php
> +        protected function AvailableActions()
Было правильное название функции - getAvailableActions. Почему поменял на AvailableActions? Это не в стиле camelCase, и хуже понятна суть - получение списка - из-за отсутствия слова get.

2020-06-01 16:43 UTC, IgorRusaleev commented on composer.json
> +    "name": "igor-rusaleev/task-force",
+++. исправил. Переустанавливал систему, поэтому composer устанавливал заново и установил с ошибками

2020-06-01 16:48 UTC, IgorRusaleev commented on src/Action/Cancel.php
> +    protected $idPerformer;
Используются в public function checkingUserStatus($idPerformer, $idCustomer, $idUser)
    {
        return ($idUser !== $idPerformer);
    }
Не понял изменить тип на другой? Тип поменял.

2020-06-01 18:36 UTC, IgorRusaleev commented on src/Task.php
> +        protected function AvailableActions()
+++

2020-06-03 18:29 UTC, IgorRusaleev commented on src/Task.php
> +        protected function AvailableActions()
+++

2020-06-03 18:29 UTC, IgorRusaleev commented on src/Action/Cancel.php
> +    public function checkingUserStatus($idPerformer, $idCustomer, $idUser)
+++

2020-06-04 06:15 UTC, nikserg requested changes
Критичное замечание - насчет возвращаемого значения getAvailableActions

2020-06-04 06:15 UTC, nikserg commented on src/Task.php
> +                if ((new Respond())->checkingUserStatus($idPerformer, $idCustomer, $idUser))
Вижу, ты не учел мое замечание выше:

$availableActions = [new ActionRespond(), new ActionCancel()];

Метод должен возвращать массив объектов. Сейчас он возвращает не-массив из одной строки. Попробуй протестировать эту функцию, поймешь, о чем я говорю.

2020-06-04 06:15 UTC, nikserg commented on src/test.php
> +var_dump($strategy->getAvailableAction()); //возвращающение статуса в который перейдет задание
Тестирование должно содержать выражение assert. Именно оно обеспечивает тестирование. Ты должен проверить на true/false какое-то выражение. Например, что функция getAvailableAction возвращает конкретные actions при конкретных начальных условиях.

2020-06-04 19:22 UTC, IgorRusaleev commented on src/Task.php
> +                if ((new Respond())->checkingUserStatus($idPerformer, $idCustomer, $idUser))
+++

2020-06-04 19:26 UTC, IgorRusaleev commented on src/test.php
> +var_dump($strategy->getAvailableAction()); //возвращающение статуса в который перейдет задание
с assert у меня какая-то проблема на компьютере, на первых заданиях он тоже не работал, и сейчас ничего не показывает. Но при тестировании через var_damp, выдает правильный ответ: string(13) "action_refuse"

2020-06-05 07:50 UTC, nikserg commented on src/Action/Cancel.php
> +    protected $idPerformer;
Они не используются в функции. В функции у тебя используются переданные в качестве параметров переменные.

2020-06-05 07:54 UTC, nikserg requested changes
Разрешил старые дискуссии, написал новые комментарии и отписался еще по старым.

2020-06-05 07:54 UTC, nikserg commented on src/Task.php
> +                    return $availableAction = $action->internalNameOfAction();
`return $availableAction = $action->internalNameOfAction();` ничем не отличается от `return $availableAction = $action->internalNameOfAction();` 
А второе проще.

2020-06-05 07:54 UTC, nikserg commented on src/test.php
> +var_dump($strategy->getAvailableAction()); //возвращающение статуса в который перейдет задание
Сделай все же assert.

2020-06-05 20:10 UTC, IgorRusaleev commented on src/Task.php
> +                    return $availableAction = $action->internalNameOfAction();
Это шутка? Если ни чем не отличается? Почему проще?))
Что не так? я не понимаю

2020-06-05 20:15 UTC, IgorRusaleev commented on src/test.php
> +var_dump($strategy->getAvailableAction()); //возвращающение статуса в который перейдет задание
сделал, но как я уже писал, assert вообще ничего в консоль не выдает

2020-06-05 20:19 UTC, IgorRusaleev commented on src/Action/Cancel.php
> +    protected $idPerformer;
+++

2020-06-17 09:46 UTC, nikserg commented on src/Task.php
> +                    return $availableAction = $action->internalNameOfAction();
Прости, ошибся, я имел в виду, можно просто написать `return $action->internalNameOfAction();`

2020-06-17 09:47 UTC, nikserg commented on src/test.php
> +var_dump($strategy->getAvailableAction()); //возвращающение статуса в который перейдет задание
var_dump - это не тестирование, это просто вывод информации. Оставь пока ассерты, пусть они не работают, позже разберемся в причинах. Для продолжения обучения это не существенно.

2020-06-17 09:50 UTC, nikserg commented
Осталось пару небольших замечаний и можно двигаться дальше!

2020-06-24 06:48 UTC, nikserg approved these changes
🎉🎉🎉

2020-06-24 06:48 UTC, merged