Исключительный тип
htmlacademy-yii/605869-task-force-1 pull request #6
Opened 2020-08-05 02:41 UTC by IgorRusaleev

2020-08-05 07:53 UTC, nikserg requested changes

2020-08-05 07:53 UTC, nikserg commented on src/Task.php
> +                if (self::STATUS_CANCEL !== $status ||
Предлагаю условие покороче: 
in_array($status, [self::STATUS_CANCEL, ...]);

2020-08-05 07:53 UTC, nikserg commented on src/ex/StatusExistsException.php
> +namespace TaskForce\ex;
ex - не очень удачное название для неймспейса с исключениями. Обычно его называют Exception.

2020-08-05 16:57 UTC, IgorRusaleev commented on src/Task.php
> +                if (self::STATUS_CANCEL !== $status ||
+++

2020-08-05 16:58 UTC, IgorRusaleev commented on src/ex/StatusExistsException.php
> +namespace TaskForce\ex;
+++

2020-08-06 06:10 UTC, nikserg approved these changes

2020-08-06 06:10 UTC, merged