Module3 task2
htmlacademy-yii/605869-task-force-1 pull request #7
Opened 2020-08-11 07:32 UTC by IgorRusaleev

2020-08-26 11:47 UTC, andrewverner requested changes

2020-08-26 11:47 UTC, denis-khodakovskiy commented on data/categories.sql
> +('');
Тебе в SQL файлы попадают пустые строки.
Надо в класс, который читает данные из CSV добавить проверку на пустую строку, чтобы они не попадали в массив, который потом пишется в SQL

2020-08-26 11:47 UTC, denis-khodakovskiy commented on src/Action/AbstractSelectingAction.php
> +    abstract public function nameOfAction(
Предлагаю переименовать в `getActionTitle`

2020-08-26 11:47 UTC, denis-khodakovskiy commented on src/Action/AbstractSelectingAction.php
> +    abstract public function internalNameOfAction(
А этот в `getActionCode`

2020-08-26 11:47 UTC, andrewverner commented on src/Import/ImportCsvToSql.php
> +            throw new FileFormatException("Заданы неверные заголовки столбцов");
У PHP есть такое понятие, как *интерполяция переменных в строке*. В строку, которая находится в двойных кавычках можно подставлять переменные из кода, не использую конкатенацию (символ точки между строками)
```
$amount = 7;
$petType = 'cat';

echo "I have {$amount} black {$petType}s";
```
Выведет `I have 7 black cats`

Если строка находится в одинарных кавычках, то переменные не интерполируются.
```
$name = 'Вася';

echo 'Hello, {$name}!';
```
Выведет `Hello, {$name}!`.


Поэтому двойные кавычки лучше использовать только в том случае, если тебе надо интерполировать переменные в строку. В остальных случаях использовать одинарные кавычки. На обработку строк в двойных кавычках уходит немного больше времени и памяти

2020-08-26 11:47 UTC, andrewverner commented on src/Import/ImportCsvToSql.php
> +        $header_data = $this->getHeaderData();
По PSR: имена переменных, свойств и методов должны писаться в нотации `camelCase`, т.е. `$headerData`

2020-08-26 11:47 UTC, andrewverner commented on src/Import/ImportCsvToSql.php
> +                }, $val));
Имена переменных лучше не сокращать, а писать полностью - правила "хорошего тона"
`$val` -> `$values`. В этой строке ещё лишний отступ

2020-08-26 11:47 UTC, andrewverner commented on src/Import/ImportCsvToSql.php
> +        return $this->fileObject->fgetcsv();
`return` всегда надо отбивать от предыдущего кода пустой строкой. Исключение составляет только методы, где кроме `return` больше ничего нет.
```php
/** @return bool */
public function isNew()
{
    return $this->status === self::STATUS_NEW;
}
```

Но
```php
/** @return float */
public function sum($a, $b)
{
    $result = $a + $b;

    return $result;
}
```

2020-08-26 11:47 UTC, andrewverner commented on src/Import/ImportCsvToSql.php
> +        $result = null;
Зачем это здесь? `$result` нигде не используется

2020-08-26 11:47 UTC, andrewverner commented on src/Import/ImportCsvToSql.php
> +        return $result;
В таких случаях лучше использовать так называемый "ранний возврат". То есть, сначала проверяются все "негативные варианты" и только потом описывается логика метода, соответствующая "позитивному" варианту, т.е.
```
private function validateColumns($columns): bool
{
    if (!count($columns)) { // "негативный" вариант
        return false; // тут работа метода обрывается и сразу возвращается false. Дальше код не выполняется
    }

    foreach ($columns as $column) {
        if (!is_string($column)) { // "негативный" вариант
            return false;
        }
    }

    // далее следует код "позитивного" варианта
    return true;
}
```

2020-08-26 11:47 UTC, andrewverner commented on src/Import/ImportCsvToSql.php
> +}
PSR: любой php-файл должен иметь в конце пустую строку

2020-08-26 11:47 UTC, andrewverner commented on src/Task.php
> +     * @var array AbstractSelectingAction
Если нужно указать, что переменная может иметь несколько разных типов, то пишут так:
`/** @var int|string|null */`

Если же переменная - массив строк, объектов или любых других типов, то пишут так:
массив чисел
`/** @var int[] */`
массив строк
`/** @var string[] */`
массив объектов Task
`/** @var Task[] */`

2020-08-26 11:47 UTC, andrewverner commented on src/Task.php
> +     * @param $status string
При описании аргументов, сначала пишут его тип, потом имя
```
@param int $userId
@param string $status
```

2020-08-26 11:47 UTC, andrewverner commented on src/Task.php
> +        return $status;
Есть вопросы и комментарии по этому методу. Лучше в скайпе обсудить

2020-08-26 11:47 UTC, andrewverner commented on src/Task.php
> +        $idUser = $this->idUser;
Эти "переменные-посредники" тут лишние.
Ты с ними ничего не делаешь - только передаёшь в метод `checkingUserStatus`. Поэтому их можно удалить, а в `checkingUserStatus` передавать так:
`$action->checkingUserStatus($this->idPerformer, $this->idCustomer, $this->idUser)`

2020-08-26 11:47 UTC, andrewverner commented on testCsvToSql.php
> +$filenames = ['categories.csv', 'cities.csv', 'opinions.csv', 'profiles.csv', 'replies.csv', 'tasks.csv', 'users.csv'];
Предлагаю сделать тут немного по-другому. Если у тебя в папке будет 150 файлов, то не удобно будет вписывать все их названия в код. У PHP есть функция [scandir](https://www.php.net/manual/en/function.scandir), которая возвращает массив файлов в папке
`$files = scandir('data');`
Но, кроме файлов, массив будет содержать ещё ссылки на текущий каталог и каталог-родитель, т.е.
```php
$files = [
    '.', // ссылка на текущий каталог
    '..', // ссылка на каталог-родитель
    'categories.csv',
    'cities.csv',
];
```
Поэтому в `foreach` нужна будет проверка на эти ссылки, чтобы их пропустить
```php
foreach ($files as $file) {
    if ($file === '.' || $file === '..') {
        continue;
    }
}
```

Или есть ещё функция [glob](https://www.php.net/manual/en/function.glob.php), которая возвращает массив файлов, подходящих по маске
`$files = glob('data/*.csv');` вернёт массив только с CSV-файлами

2020-08-26 11:47 UTC, andrewverner commented on testCsvToSql.php
> +    $ImportCsvToSql = new ImportCsvToSql($filename, $columns);
Имена переменных должны начинаться с букв нижнего регистра `$importCsvToSql`

2020-08-26 11:47 UTC, andrewverner commented on src/Import/ImportCsvToSql.php
> +class ImportCsvToSql
Класс лучше переименовать. `ImportCsvToSql` не совсем соответствует сути класса
1. импорт - ввоз товара из-за границы, тут больше подошёл бы **экспорт**, потому как ты данные из одних файлов переводишь в другие
2. сам по себе класс ничего не импортирует и не экспортирует. Он считывает данные из одних файлов и конвертирует эти данные в другой формат

Поэтому тут лучше использовать `Parser` или `Converter`, т.е. `CsvToSqlParser` или `CsvToSqlConverter`

2020-08-27 16:52 UTC, IgorRusaleev commented on data/categories.sql
> +('');
+++ в checkFile добавил проверку на пустую строку

2020-08-27 17:09 UTC, IgorRusaleev commented on src/Action/AbstractSelectingAction.php
> +    abstract public function nameOfAction(
+++ переименовал

2020-08-27 17:13 UTC, IgorRusaleev commented on src/Action/AbstractSelectingAction.php
> +    abstract public function internalNameOfAction(
+++ переименовал

2020-08-27 17:37 UTC, IgorRusaleev commented on src/Import/ImportCsvToSql.php
> +            throw new FileFormatException("Заданы неверные заголовки столбцов");
+++ исправил

2020-08-27 17:43 UTC, IgorRusaleev commented on src/Import/ImportCsvToSql.php
> +        $header_data = $this->getHeaderData();
+++ исправил

2020-08-27 17:56 UTC, IgorRusaleev commented on src/Task.php
> +        $idUser = $this->idUser;
+++ исправил

2020-08-27 19:48 UTC, IgorRusaleev commented on testCsvToSql.php
> +$filenames = ['categories.csv', 'cities.csv', 'opinions.csv', 'profiles.csv', 'replies.csv', 'tasks.csv', 'users.csv'];
Применив 
foreach (glob('data/*.csv') as $file) {
    $filenames = ltrim($file, "data/");
}
собрал массив csv файлов. Появилась проблема с импортом в sql. В следующем foreach  $filenames не определен. Почему?

2020-08-27 19:50 UTC, IgorRusaleev commented on testCsvToSql.php
> +    $ImportCsvToSql = new ImportCsvToSql($filename, $columns);
+++ исправил

2020-08-27 19:58 UTC, IgorRusaleev commented on src/Import/ImportCsvToSql.php
> +class ImportCsvToSql
+++ исправил

2020-08-27 19:59 UTC, IgorRusaleev commented on src/Task.php
> +        return $status;
Когда?

2020-09-01 18:21 UTC, IgorRusaleev commented on src/Task.php
> +     * @var array AbstractSelectingAction
+++

2020-09-01 18:30 UTC, IgorRusaleev commented on src/Import/ImportCsvToSql.php
> +                }, $val));
+++ переименовал переменую

2020-09-01 18:34 UTC, IgorRusaleev commented on src/Import/ImportCsvToSql.php
> +        return $this->fileObject->fgetcsv();
+++ исправил

2020-09-01 18:40 UTC, IgorRusaleev commented on src/Import/ImportCsvToSql.php
> +        $result = null;
этот метод скопировал из учебника. только упустил: return $result
добавил

2020-09-01 18:48 UTC, IgorRusaleev commented on src/Import/ImportCsvToSql.php
> +        return $result;
не понял как переделать

2020-09-01 18:50 UTC, IgorRusaleev commented on src/Import/ImportCsvToSql.php
> +}
+++ исправил

2020-09-01 18:53 UTC, IgorRusaleev commented on src/Task.php
> +     * @param $status string
+++ исправил

2020-09-08 16:54 UTC, merged